# Release Hash Manifest

[release]
name = "FileCabinet_msix"
version = "0.1.1.0"
artifact = "file-cabinet_0.1.1.0_x64.msix"
path = "D:\\DRS\\File Cabinet\\file-cabinet_0.1.1.0_x64.msix"
size_bytes = 10623321

[[hash]]
algorithm = "SHA256"
value = "cfbaf1b290540ef1a472fb9f934d3096707a51ee4fab289055559d1894b36727"

[[hash]]
algorithm = "BLAKE3-256"
value = "1588327aa71aa1e2f0fa8f95831457a75ffc578f8921f606250f6d2067309ad9"

[[hash]]
algorithm = "KT128"
value = "4eB9o9kw5VUtIB0mE/opsQy2qTjyiETvNRjjYpdkLtBBEMYOr+QwerbtxzDY2h+jyHo9YjK9ozY6h7z3Q1b4CgQ79tla8LbbKVs2q6X81yBhOhJD5/NUrcl9x7Di3gHIJJ7c+if2zMkZR4mSzw18PM8mdXndI81uS5hjdnzziEM="
