# Release Hash Manifest

[release]
name = "FilingCabinet"
version = "0.1.1.0"
artifact = "Aptlantis.FilingCabinet_0.1.1.0_x64.msix"
path = "D:\\DRS\\File Cabinet\\Aptlantis.FilingCabinet_0.1.1.0_x64.msix"
size_bytes = 9900554

[[hash]]
algorithm = "SHA256"
value = "0ec8e3bdfbd391da466945f3acc09836989fe43ff9f31852f33b73568c592694"

[[hash]]
algorithm = "BLAKE3-256"
value = "adb67602c9b0faa0566bbf5ddeb84de3ddb409bdaf981290a6bdeb4dbdc33b1d"

[[hash]]
algorithm = "KT128"
value = "eQ/1ZYAYcxCpGVHizkCLrCvowRWzdCZ2DSRRCbcjnd8JE0acfLGFMgubrIzZlivXS81I78VUmZpaZsfCbG74Iv+yyfFDImN0Wkg8CAsfLNu/46mrNoiGD1LAhho6xyrE/s2OrBSJMAYeUXVyYAhJUvOZ5Ot0jERXNI6GrRi06vs="
