Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports System.IO

Namespace FileCabinet.Tests
    <TestClass>
    Public Class DeterminismTests
        <TestMethod>
        Sub CatalogRoundTripPreservesArtifactOrderIdentityHashesAndOperatorMetadata()
            Using workspace As New TestWorkspace()
                Dim service As New Global.FileCabinet.CatalogService(workspace.CatalogPath, workspace.VaultRoot)
                Dim catalog = service.LoadOrCreate()
                Dim firstPath = workspace.VaultItemPath("first.txt")
                Dim secondPath = workspace.VaultItemPath("second.txt")
                File.WriteAllText(firstPath, "first")
                File.WriteAllText(secondPath, "second")

                Dim first = TestVaultFixtures.CompleteArtifact("artifact-a", "first.txt", firstPath, workspace.VaultRoot, "source\first.txt")
                first.RetentionReason = "Keep the first fixture"
                first.WhyThisMatters = "It proves order is stable"
                first.SourceProvenance = "Fixture source A"
                first.AcquisitionMethod = "Generated by test"
                first.TrustClassification = "Trusted"
                first.RetentionPriority = "High"
                first.ArchiveStatus = "Archived"

                Dim second = TestVaultFixtures.CompleteArtifact("artifact-b", "second.txt", secondPath, workspace.VaultRoot, "source\second.txt")
                second.RetentionReason = "Keep the second fixture"
                second.TrustClassification = "Questionable"
                second.RetentionPriority = "Review later"
                second.ArchiveStatus = "Needs review"

                catalog.Artifacts.Add(first)
                catalog.Artifacts.Add(second)
                service.Save(catalog)

                Dim reloaded = service.LoadOrCreate()

                Assert.AreEqual(2, reloaded.Artifacts.Count)
                Assert.AreEqual("artifact-a", reloaded.Artifacts(0).Id)
                Assert.AreEqual("artifact-b", reloaded.Artifacts(1).Id)
                Assert.AreEqual(first.Sha256, reloaded.Artifacts(0).Sha256)
                Assert.AreEqual(first.Blake3, reloaded.Artifacts(0).Blake3)
                Assert.AreEqual(first.RelativePath, reloaded.Artifacts(0).RelativePath)
                Assert.AreEqual("Keep the first fixture", reloaded.Artifacts(0).RetentionReason)
                Assert.AreEqual("It proves order is stable", reloaded.Artifacts(0).WhyThisMatters)
                Assert.AreEqual("Fixture source A", reloaded.Artifacts(0).SourceProvenance)
                Assert.AreEqual("Generated by test", reloaded.Artifacts(0).AcquisitionMethod)
                Assert.AreEqual("Trusted", reloaded.Artifacts(0).TrustClassification)
                Assert.AreEqual("High", reloaded.Artifacts(0).RetentionPriority)
                Assert.AreEqual("Archived", reloaded.Artifacts(0).ArchiveStatus)
                Assert.AreEqual("Questionable", reloaded.Artifacts(1).TrustClassification)
                Assert.AreEqual("Review later", reloaded.Artifacts(1).RetentionPriority)
                Assert.AreEqual("Needs review", reloaded.Artifacts(1).ArchiveStatus)
            End Using
        End Sub

        <TestMethod>
        Sub DuplicateDiscoveryDependsOnSha256Equality()
            Using workspace As New TestWorkspace()
                Dim catalog = TestVaultFixtures.DuplicateFileVault(workspace)
                Dim first = catalog.Artifacts(0)
                Dim second = catalog.Artifacts(1)
                second.Blake3 = "different-blake3"

                Assert.IsTrue(Global.FileCabinet.MainViewModel.ArtifactMatchesDiscoveryScope(first, "Duplicate candidates", catalog.Artifacts, workspace.VaultRoot))

                second.Sha256 = "different-sha256"

                Assert.IsFalse(Global.FileCabinet.MainViewModel.ArtifactMatchesDiscoveryScope(first, "Duplicate candidates", catalog.Artifacts, workspace.VaultRoot))
            End Using
        End Sub

        <TestMethod>
        Sub HealthFindingsAndRepairCandidatesKeepStableOrderForCoreIntegritySignals()
            Using workspace As New TestWorkspace()
                Dim missing = TestVaultFixtures.CompleteArtifact("artifact-missing", "missing.iso", workspace.VaultItemPath("missing.iso"), workspace.VaultRoot, "source\missing.iso")
                missing.Sha256 = "duplicate-sha256"
                missing.Blake3 = "missing-blake3"

                Dim retainedPath = workspace.VaultItemPath("kept.txt")
                File.WriteAllText(retainedPath, "retained content")
                Dim mismatch = TestVaultFixtures.CompleteArtifact("artifact-kept", "kept.txt", retainedPath, workspace.VaultRoot, "source\kept.txt")
                mismatch.Sha256 = "duplicate-sha256"
                mismatch.Blake3 = "wrong-blake3"

                Dim report = Global.FileCabinet.MainViewModel.BuildVaultHealthReport(
                    {missing, mismatch},
                    workspace.VaultRoot,
                    New Global.FileCabinet.ThumbnailService(),
                    New Global.FileCabinet.HashService())

                Dim orderedFindings = report.Findings.Select(Function(finding) $"{finding.FindingType}:{finding.Subject}").ToList()
                CollectionAssert.AreEqual(
                    New List(Of String) From {
                        "Missing file:missing.iso",
                        "Hash mismatch:kept.txt",
                        "Duplicate hash:duplicate-sha256"
                    },
                    orderedFindings)

                Dim repairCandidates = report.Findings.Select(Function(finding) Global.FileCabinet.MainViewModel.BuildRepairCandidate(finding)).ToList()
                CollectionAssert.AreEqual(
                    orderedFindings,
                    repairCandidates.Select(Function(candidate) $"{candidate.FindingType}:{candidate.Subject}").ToList())
            End Using
        End Sub
    End Class
End Namespace
